'use strict';
const API_BASE='';
const USERS={WINTIQ_MASTER:{password:'W!ntiqMaster#2026X',role:'admin'},Ionix87:{password:'Ajjw_291#12_O9s',role:'user'},Sxne1:{password:'K211093##duik_',role:'user'}};
const DEFAULTS={heroTitle:'SPORT.\nDATA.\nMOMENTUM.',heroText:'Live-Kontext, klare Daten und redaktionelle Picks. Alles, was du im Moment wissen willst — ohne visuelles Chaos.',release:'2026-09-13',pulse:'Live intelligence',picks:[{id:'pick-1',sport:'FUSSBALL',match:'FC Bayern — Dortmund',tip:'Heimsieg',reason:'WINTIQ Edge: Heimvorteil, Druckphase und aktuelle Matchdynamik sprechen für das Heimteam.',tag:'TOP PICK',odd:'1.78',startAt:'2026-09-12T22:00:00+02:00',durationMinutes:105},{id:'pick-2',sport:'TENNIS',match:'Spieler A — Spieler B',tip:'Spieler A',reason:'WINTIQ Edge: stärkerer Start und bessere Punktquote in den entscheidenden Ballwechseln.',tag:'EDGE',odd:'1.85',startAt:'2026-09-13T18:00:00+02:00',durationMinutes:120},{id:'pick-3',sport:'BASKETBALL',match:'Lakers — Celtics',tip:'Lakers',reason:'WINTIQ Edge: Matchup und Home-Court-Faktor geben dem Pick einen kleinen Vorteil.',tag:'WATCH',odd:'1.92',startAt:'2026-09-13T20:30:00+02:00',durationMinutes:150}]};
let state=loadState(),liveFeed={updatedAt:null,refreshSeconds:5,matches:{}};let currentUser=null;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function loadState(){try{const s=JSON.parse(localStorage.getItem('wintiqState')||'null');return {...structuredClone(DEFAULTS),...(s||{}),picks:Array.isArray(s?.picks)?s.picks:structuredClone(DEFAULTS.picks)}}catch{return structuredClone(DEFAULTS)}}
function saveState(){localStorage.setItem('wintiqState',JSON.stringify(state))}
function toast(msg){const e=$('#toast');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),3000)}
function fmtDate(ts,withTime=true){if(!Number.isFinite(ts))return'—';return new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric',...(withTime?{hour:'2-digit',minute:'2-digit'}:{})}).format(new Date(ts))}
function fmtClock(ts){return Number.isFinite(ts)?new Intl.DateTimeFormat('de-DE',{hour:'2-digit',minute:'2-digit'}).format(new Date(ts)):'—'}
function fmtDuration(ms){if(!Number.isFinite(ms)||ms<=0)return'00:00';let s=Math.ceil(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`:`${m}:${String(sec).padStart(2,'0')}`}
function teams(p){const x=String(p.match||'').split(/\s+[—–-]\s+/);return{home:x[0]||'Team A',away:x[1]||'Team B'}}
function feedMatch(i,p){return liveFeed.matches?.[p.id||`pick-${i+1}`]||liveFeed.matches?.[`pick-${i+1}`]||null}
function liveState(p,i){const f=feedMatch(i,p),start=new Date(p.startAt||'').getTime(),duration=Math.max(60,Number(p.durationMinutes)||105),end=start+duration*60000,now=Date.now();if(f?.status==='live'){const fs=new Date(f.startedAt||p.startAt||'').getTime();const minute=Number.isFinite(fs)?Math.min(duration,Math.max(1,Math.floor((now-fs)/60000)+1)):Number(f.minute)||1;return{status:'live',start,end,duration,minute,remaining:Math.max(0,end-now),feed:f}}if(f?.status==='upcoming')return{status:'upcoming',start,end,duration,minute:0,remaining:Math.max(0,start-now),feed:f};if(f?.status==='finished')return{status:'finished',start,end,duration,minute:duration,remaining:0,feed:f};if(now<start)return{status:'upcoming',start,end,duration,minute:0,remaining:start-now,feed:f};if(now<end)return{status:'live',start,end,duration,minute:Math.floor((now-start)/60000)+1,remaining:end-now,feed:f};return{status:'finished',start,end,duration,minute:duration,remaining:0,feed:f}}
function score(p,i,l){const f=l.feed;if(f?.score&&Number.isFinite(+f.score.home)&&Number.isFinite(+f.score.away))return[+f.score.home,+f.score.away];return[0,0]}
function verdict(p,i,l){if(l.status==='upcoming')return'pending';if(p.result==='won'||p.result==='lost')return p.result==='won'?'correct':'wrong';const[s1,s2]=score(p,i,l),t=String(p.tip||'').toLowerCase();if(t.includes('auswärt')||t.includes('away'))return s2>s1?'correct':'wrong';if(t.includes('draw')||t.includes('unentschieden'))return s1===s2?'correct':'wrong';return s1>s2?'correct':'wrong'}
function dateLabel(l){if(l.status==='upcoming')return`Start ${fmtDate(l.start)}`;if(l.status==='live')return`Seit ${fmtClock(l.start)}`;return`War am ${fmtDate(l.start)}`}
function events(feed){const ev=Array.isArray(feed?.events)?feed.events.slice(-4).reverse():[];if(!ev.length)return'';return`<div class="pick-events"><div class="kicker">LIVE EVENTS</div>${ev.map(e=>`<div class="pick-event"><b>${esc(e.minute??'—')}'</b><span>${e.type==='goal'?'⚽':e.type==='card'?'🟨':'•'}</span><span>${esc(e.text||e.type||'Event')}</span></div>`).join('')}</div>`}
function liveCard(p,i){const l=liveState(p,i),s=score(p,i,l),v=verdict(p,i,l),t=teams(p);let status=l.status==='live'?`LIVE · ${l.minute}'`:l.status==='upcoming'?'STARTET BALD':'BEENDET';let result=l.status==='live'?(v==='correct'?'✓ AKTUELL RICHTIG':v==='wrong'?'✕ AKTUELL FALSCH':'◌ NOCH OFFEN'):(l.status==='finished'?(v==='correct'?'✓ PICK RICHTIG':'✕ PICK FALSCH'):'◌ NOCH OFFEN');return`<div class="pick-live-card"><div class="pick-live-head"><span class="status ${l.status}">${status}</span><span class="sport-mini">${esc(p.sport)}</span></div><div class="score-row"><span class="team">${esc(t.home)}</span><strong class="score">${s[0]} <small>:</small> ${s[1]}</strong><span class="team">${esc(t.away)}</span></div><div class="live-meta"><div>📅 DATUM<b>${esc(fmtDate(l.start,false))}</b></div><div>🕐 ZEIT<b>${esc(fmtClock(l.start))}</b></div><div>⏱ STATUS<b>${l.status==='live'?`${l.minute}' · ${fmtDuration(l.remaining)} übrig`:l.status==='upcoming'?`in ${fmtDuration(l.remaining)}`:'Endstand'}</b></div><div>📍 PHASE<b>${l.status==='live'?'LIVE':l.status==='upcoming'?'UPCOMING':'FINISHED'}</b></div></div><div class="verdict ${v}">${result}</div>${events(l.feed)}</div>`}
function renderTicker(){const box=$('#picksLiveTicker');if(!box)return;const ps=state.picks||[];const make=(p,i)=>{const l=liveState(p,i),s=score(p,i,l),t=teams(p),label=l.status==='live'?`LIVE · ${l.minute}'`:l.status==='upcoming'?'STARTET BALD':'BEENDET',sub=l.status==='live'?`${s[0]} : ${s[1]} · ${fmtDuration(l.remaining)} übrig`:l.status==='upcoming'?`📅 ${fmtDate(l.start)}`:`Endstand ${s[0]} : ${s[1]}`;return`<div class="rail-item ${l.status}"><span class="rail-state">${label}</span><strong class="rail-match">${esc(t.home)} <b>${s[0]}:${s[1]}</b> ${esc(t.away)}</strong><small class="rail-sub">${esc(sub)}</small></div>`};const html=ps.map(make).join('');box.innerHTML=`<div class="rail-viewport"><div class="rail-track"><div class="rail-set">${html}</div><div class="rail-set" aria-hidden="true">${html}</div></div></div>`}
function renderPicks(){const g=$('#pickGrid');if(!g)return;g.innerHTML=(state.picks||[]).map((p,i)=>`<article class="pick-card"><div class="pick-inner"><div class="pick-top"><span class="pick-tag">${esc(p.tag||'PICK')}</span><span class="pick-number">#${String(i+1).padStart(2,'0')}</span></div><div class="pick-sport">${esc(p.sport||'SPORT')}</div><div class="pick-match">${esc(p.match)}</div><div class="pick-tip"><span>🎯 WINTIQ TIPP</span><strong>${esc(p.tip)}</strong></div><div class="pick-reason">📝 ${esc(p.reason)}</div><div class="pick-bottom"><span>QUOTE</span><strong>${esc(p.odd||'—')}</strong></div>${liveCard(p,i)}</div></article>`).join('');renderTicker()}
function renderMatchBoard(){const b=$('#matchBoard');if(!b)return;const ps=state.picks||[];b.innerHTML=ps.map((p,i)=>{const l=liveState(p,i),s=score(p,i,l),t=teams(p);return`<div class="match-row"><span class="match-status ${l.status}">${l.status==='live'?`● LIVE ${l.minute}'`:l.status==='upcoming'?'UPCOMING':'FINISHED'}</span><span class="match-teams">${esc(t.home)}</span><strong class="match-score">${s[0]}:${s[1]}</strong><span class="match-teams away">${esc(t.away)}</span><span class="match-time">${l.status==='live'?`${fmtDuration(l.remaining)} übrig`:fmtDate(l.start)}</span></div>`}).join('')}
function updateLive(){renderPicks();renderMatchBoard();const now=liveFeed.updatedAt?new Date(liveFeed.updatedAt).getTime():0;$('#lastUpdate').textContent=now?`FEED · ${fmtClock(now)}`:'FEED · LOCAL';$('#feedSync').textContent=now?'SYNCED':'LOCAL';$('#tickerUpdated').textContent=`Zuletzt geprüft ${new Date().toLocaleTimeString('de-DE')}`;const live=(state.picks||[]).filter((p,i)=>liveState(p,i).status==='live').length;$('#heroLiveCount').textContent=live;$('#heroPickCount').textContent=(state.picks||[]).length;$('#heroFeedAge').textContent=liveFeed.updatedAt?'ONLINE':'LOCAL'}
async function loadLiveFeed(){try{const r=await fetch(`live-data.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();liveFeed={...liveFeed,...d,matches:{...(liveFeed.matches||{}),...(d.matches||{})}};updateLive()}catch(e){updateLive()}}
function renderHero(){const title=$('#heroTitle');title.innerHTML=esc(state.heroTitle).replace(/\n/g,'<br>');$('#heroText').textContent=state.heroText;$('#pulseText').textContent=state.pulse;$('#releaseMeta').textContent=state.release;$('#releaseDateBig').textContent=state.release;}
function countdown(){const target=new Date(`${state.release}T00:00:00`).getTime(),d=Math.max(0,target-Date.now()),s=Math.floor(d/1000),days=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60),sec=s%60,p=x=>String(x).padStart(2,'0');$('#timer').textContent=`${p(days)} : ${p(h)} : ${p(m)} : ${p(sec)}`;$('#days').textContent=`${p(days)} DAYS`}
function unlock(user,role){currentUser={user,role};sessionStorage.setItem('wintiqUser',JSON.stringify(currentUser));document.body.classList.remove('locked');$('#loginGate').classList.add('hidden');$('#app').classList.remove('app-hidden');$('#currentUserLabel').textContent=user+(role==='admin'?' · ADMIN':'');if(role==='admin')$('#adminOpen').classList.remove('hidden')}
function lock(){sessionStorage.removeItem('wintiqUser');currentUser=null;document.body.classList.add('locked');$('#loginGate').classList.remove('hidden');$('#app').classList.add('app-hidden');closeModal('#adminPanel');closeModal('#resetModal')}
function closeModal(id){$(id)?.classList.add('hidden')}
function resetRequest(){const u=$('#resetUsername').value.trim(),m=$('#resetMessage');if(!u||!USERS[u]){m.textContent='Benutzername nicht gefunden.';m.style.color='#ff6d75';return}let r=JSON.parse(localStorage.getItem('wintiqPasswordRequests')||'[]');if(!r.some(x=>x.username===u&&x.status==='pending'))r.unshift({id:'PW-'+Date.now().toString(36),username:u,status:'pending',createdAt:new Date().toISOString()});localStorage.setItem('wintiqPasswordRequests',JSON.stringify(r));m.textContent='Anfrage gesendet ✓';m.style.color='var(--acid)';toast('Passwort-Anfrage gesendet');setTimeout(()=>closeModal('#resetModal'),900)}
function renderAdmin(){if(!currentUser||currentUser.role!=='admin')return;$('#aHeroTitle').value=state.heroTitle;$('#aHeroText').value=state.heroText;$('#aRelease').value=state.release;$('#aPulse').value=state.pulse;$('#adminPicks').innerHTML=state.picks.map((p,i)=>`<div class="password-request"><div class="password-request-top"><b>Pick ${i+1}</b><button class="mini-btn" data-remove-pick="${i}">ENTFERNEN</button></div><div class="admin-grid"><label>Sport<input data-p="${i}" data-f="sport" value="${esc(p.sport)}"></label><label>Tag<input data-p="${i}" data-f="tag" value="${esc(p.tag||'PICK')}"></label><label>Match<input data-p="${i}" data-f="match" value="${esc(p.match)}"></label><label>Tipp<input data-p="${i}" data-f="tip" value="${esc(p.tip)}"></label><label>Startzeit<input type="datetime-local" data-p="${i}" data-f="startAt" value="${esc((p.startAt||'').slice(0,16))}"></label><label>Dauer<input type="number" data-p="${i}" data-f="durationMinutes" value="${esc(p.durationMinutes||105)}"></label><label>Quote<input data-p="${i}" data-f="odd" value="${esc(p.odd||'')}"></label><label>Einschätzung<textarea data-p="${i}" data-f="reason" rows="2">${esc(p.reason||'')}</textarea></label></div></div>`).join('');document.querySelectorAll('[data-p]').forEach(e=>e.oninput=()=>{const i=+e.dataset.p;state.picks[i][e.dataset.f]=e.dataset.f==='durationMinutes'?+e.value:e.value});renderRequests()}
function renderRequests(){const list=$('#passwordRequestList'),r=JSON.parse(localStorage.getItem('wintiqPasswordRequests')||'[]');$('#pendingResetCount').textContent=r.filter(x=>x.status==='pending').length;if(!r.length){list.innerHTML='<div class="password-request">Keine Anfragen.</div>';return}list.innerHTML=r.map(x=>`<div class="password-request"><div class="password-request-top"><b>${esc(x.username)}</b><span class="password-request-status">${esc(x.status)}</span></div><div class="password-request-meta">${esc(new Date(x.createdAt).toLocaleString('de-DE'))}</div></div>`).join('')}
function init(){renderHero();renderPicks();renderMatchBoard();countdown();$('#loginForm').onsubmit=e=>{e.preventDefault();const u=$('#loginUser').value.trim(),p=$('#loginPass').value;if(USERS[u]?.password===p)unlock(u,USERS[u].role);else $('#loginError').textContent='Benutzername oder Passwort ist falsch.'};$('#forgotPasswordBtn').onclick=()=>$('#resetModal').classList.remove('hidden');$('#resetClose').onclick=()=>closeModal('#resetModal');$('#sendResetRequest').onclick=resetRequest;$('#logout').onclick=lock;$('#hamb').onclick=()=>$('#mobile').classList.toggle('open');document.querySelectorAll('#mobile a').forEach(a=>a.onclick=()=>$('#mobile').classList.remove('open'));$('#adminOpen').onclick=()=>{$('#adminPanel').classList.remove('hidden');renderAdmin()};$('#adminClose').onclick=()=>closeModal('#adminPanel');$('#addPick').onclick=()=>{state.picks.push({id:'pick-'+Date.now(),sport:'FUSSBALL',match:'Neue Partie — Gegner',tip:'Heimsieg',reason:'Neue WINTIQ Einschätzung.',tag:'NEW',odd:'1.90',startAt:new Date(Date.now()+3600000).toISOString(),durationMinutes:105});renderAdmin()};$('#saveAdmin').onclick=()=>{state.heroTitle=$('#aHeroTitle').value;state.heroText=$('#aHeroText').value;state.release=$('#aRelease').value;state.pulse=$('#aPulse').value;saveState();renderHero();updateLive();closeModal('#adminPanel');toast('Änderungen gespeichert ✓')};$('#resetAdmin').onclick=()=>{state=structuredClone(DEFAULTS);saveState();renderAdmin();renderHero();updateLive()};$('#refreshPasswordRequests').onclick=renderRequests;$('#adminPicks').onclick=e=>{const b=e.target.closest('[data-remove-pick]');if(b){state.picks.splice(+b.dataset.removePick,1);renderAdmin()}};['#testGitHub','#publishGitHub'].forEach(id=>$(id).onclick=()=>toast('GitHub-Funktion ist in dieser Demo vorbereitet.'));try{const s=JSON.parse(sessionStorage.getItem('wintiqUser')||'null');if(s?.user&&USERS[s.user])unlock(s.user,USERS[s.user].role)}catch{};loadLiveFeed();setInterval(()=>{countdown();updateLive()},1000);setInterval(loadLiveFeed,5000)}
document.addEventListener('DOMContentLoaded',init);
